/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as MainRouteImport } from './routes/_main'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SesionFridgeIdRouteImport } from './routes/sesion.$fridgeId'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as MainTarjetasRouteImport } from './routes/_main.tarjetas'
import { Route as MainHistorialRouteImport } from './routes/_main.historial'
import { Route as MainHeladerasRouteImport } from './routes/_main.heladeras'
import { Route as MainHistorialTxIdRouteImport } from './routes/_main.historial.$txId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SesionFridgeIdRoute = SesionFridgeIdRouteImport.update({
  id: '/sesion/$fridgeId',
  path: '/sesion/$fridgeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const MainTarjetasRoute = MainTarjetasRouteImport.update({
  id: '/tarjetas',
  path: '/tarjetas',
  getParentRoute: () => MainRoute,
} as any)
const MainHistorialRoute = MainHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => MainRoute,
} as any)
const MainHeladerasRoute = MainHeladerasRouteImport.update({
  id: '/heladeras',
  path: '/heladeras',
  getParentRoute: () => MainRoute,
} as any)
const MainHistorialTxIdRoute = MainHistorialTxIdRouteImport.update({
  id: '/$txId',
  path: '/$txId',
  getParentRoute: () => MainHistorialRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/heladeras': typeof MainHeladerasRoute
  '/historial': typeof MainHistorialRouteWithChildren
  '/tarjetas': typeof MainTarjetasRoute
  '/admin/login': typeof AdminLoginRoute
  '/sesion/$fridgeId': typeof SesionFridgeIdRoute
  '/admin/': typeof AdminIndexRoute
  '/historial/$txId': typeof MainHistorialTxIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/heladeras': typeof MainHeladerasRoute
  '/historial': typeof MainHistorialRouteWithChildren
  '/tarjetas': typeof MainTarjetasRoute
  '/admin/login': typeof AdminLoginRoute
  '/sesion/$fridgeId': typeof SesionFridgeIdRoute
  '/admin': typeof AdminIndexRoute
  '/historial/$txId': typeof MainHistorialTxIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_main': typeof MainRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_main/heladeras': typeof MainHeladerasRoute
  '/_main/historial': typeof MainHistorialRouteWithChildren
  '/_main/tarjetas': typeof MainTarjetasRoute
  '/admin/login': typeof AdminLoginRoute
  '/sesion/$fridgeId': typeof SesionFridgeIdRoute
  '/admin/': typeof AdminIndexRoute
  '/_main/historial/$txId': typeof MainHistorialTxIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/heladeras'
    | '/historial'
    | '/tarjetas'
    | '/admin/login'
    | '/sesion/$fridgeId'
    | '/admin/'
    | '/historial/$txId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/heladeras'
    | '/historial'
    | '/tarjetas'
    | '/admin/login'
    | '/sesion/$fridgeId'
    | '/admin'
    | '/historial/$txId'
  id:
    | '__root__'
    | '/'
    | '/_main'
    | '/admin'
    | '/login'
    | '/register'
    | '/_main/heladeras'
    | '/_main/historial'
    | '/_main/tarjetas'
    | '/admin/login'
    | '/sesion/$fridgeId'
    | '/admin/'
    | '/_main/historial/$txId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRoute: typeof MainRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SesionFridgeIdRoute: typeof SesionFridgeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/sesion/$fridgeId': {
      id: '/sesion/$fridgeId'
      path: '/sesion/$fridgeId'
      fullPath: '/sesion/$fridgeId'
      preLoaderRoute: typeof SesionFridgeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_main/tarjetas': {
      id: '/_main/tarjetas'
      path: '/tarjetas'
      fullPath: '/tarjetas'
      preLoaderRoute: typeof MainTarjetasRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/historial': {
      id: '/_main/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof MainHistorialRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/heladeras': {
      id: '/_main/heladeras'
      path: '/heladeras'
      fullPath: '/heladeras'
      preLoaderRoute: typeof MainHeladerasRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/historial/$txId': {
      id: '/_main/historial/$txId'
      path: '/$txId'
      fullPath: '/historial/$txId'
      preLoaderRoute: typeof MainHistorialTxIdRouteImport
      parentRoute: typeof MainHistorialRoute
    }
  }
}

interface MainHistorialRouteChildren {
  MainHistorialTxIdRoute: typeof MainHistorialTxIdRoute
}

const MainHistorialRouteChildren: MainHistorialRouteChildren = {
  MainHistorialTxIdRoute: MainHistorialTxIdRoute,
}

const MainHistorialRouteWithChildren = MainHistorialRoute._addFileChildren(
  MainHistorialRouteChildren,
)

interface MainRouteChildren {
  MainHeladerasRoute: typeof MainHeladerasRoute
  MainHistorialRoute: typeof MainHistorialRouteWithChildren
  MainTarjetasRoute: typeof MainTarjetasRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainHeladerasRoute: MainHeladerasRoute,
  MainHistorialRoute: MainHistorialRouteWithChildren,
  MainTarjetasRoute: MainTarjetasRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRoute: MainRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SesionFridgeIdRoute: SesionFridgeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
